services:
  backend:
    build: 
     context: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: api
      APP_SERVER_PORT: 8080
      APP_LOG_LEVEL: "INFO"
      DATABASE_URL: "mysql://root:@db:3306/api"
      
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: docker.io/bitnami/mysql:latest
    ports:
      - '3306:3306'
    # volumes:
    #   - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MYSQL_DATABASE: api
      ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
