"""Added color field to the groups table

Revision ID: 07f7496ef1e3
Revises: 58b6ba1f60fc
Create Date: 2023-10-01 13:57:01.735450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f7496ef1e3'
down_revision: Union[str, None] = '58b6ba1f60fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'color')
    # ### end Alembic commands ###
