"""Added added an owner fk to the groups table

Revision ID: f4fc2f57b4c1
Revises: 07f7496ef1e3
Create Date: 2023-10-01 14:16:00.887265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4fc2f57b4c1'
down_revision: Union[str, None] = '07f7496ef1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['owner'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner')
    # ### end Alembic commands ###
